server:
  port: 8081
  servlet:
    context-path: /uaa
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb0?useSSL=false
    username: root
    password: 123456
    schema-username: root
    schema-password: 123456
    data-username: root
    data-password: 123456
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
    continue-on-error: true
    initialization-mode: always
  redis:
    host: 127.0.0.1
    port: 6379
